### ISSUE TITLE
When using ampersand-model I cannot save a prop called `url`

### ISSUE THREAD

**Issue by jeremyblalock** [AmpersandJS/ampersand-model#63]
Hi,

In my application, I have an API endpoint that accepts URLs (and other parameters) in POST / PUT requests, and also returns them back in the GET request. Currently, the URL field has the name `"url"` in the API, however, and it seems there's a conflict with the model's `url()` method.

When I try to add `"url"` to the props, like:

```
var MyModel = AmpersandModel.extend({
  props: {
    url: 'String'
  }
  ...
});
```

I see that when I call `.save()` to `POST` the data (`{"url": "my-url.com"}`), the URL that we hit is:

```
/my-url.com
```

But I really want to hit `/api/urls` with the data.

Any recommendations?

**Comment by wraithgar** [comment]
The way this has been solved in the past that I know of has been translating that parameter on `parse` and `serialize` so that to your ampersand model it's named something else.

I know this is less than ideal but so far nobody has come up w/ a more elegant way of fixing this.

**Comment by pgilad** [comment]
There is no way to avoid collision since we are assigning all props|session|derived properties to the model instance, and `url` is also the name of the method or property for getting model url.

1 way to avoid collision is by remapping server properties (the way @wraithgar suggested). But this will require a transform when syncing to server again. (Very annoying).

The other way will require a patch, giving an option to turn off the assignment of all above properties to the `this` instance of the model. This will give you a chance to use any name for props|derived|session properties without ever worrying about name collisions, but you will have to access them using `model.get('url')`

**Comment by jeremyblalock** [comment]
@wraithgar we ended up going with your solution, though, I agree, it could be nice to individually turn on / off the automatic accessor generation for a particular property. May complicate the API too much though.
